### ISSUE TITLE
使用浏览器的inspect页面，选中element，按下快捷键h，水印会被隐藏

### ISSUE THREAD

**Issue by simontang** [pansyjs/watermark#112]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/1438670/171132909-f589c6f1-a55c-4548-b178-d50f5d0f5bb2.png">

**Comment by wangxingkang** [comment]
好的 我看一下

**Comment by wangxingkang** [comment]
大概知道原因了下个版本修复

**Comment by wangxingkang** [comment]
详细看了下，谷歌浏览的这个行为 会跳过 MutationObserver 的监视， 确实没法避免 ，建议将需要加水印的区域  用水印 dom 包裹
