### ISSUE TITLE
vue中如何支持全局水印

### ISSUE THREAD

**Issue by LiXunGuan** [pansyjs/watermark#127]
1、如何给整个body添加水印？
2、vue2.7 开始就自带composition-api `@vue/composition-api`我觉得可以删掉了

**Comment by yibo520Zan** [comment]
第一个我觉得可以挂在App.vue中id=“app”的div上，app宽高继承body，这样也是全局水印

**Comment by wangxingkang** [comment]
isBody 不可以吗

**Comment by LiXunGuan** [comment]
没注意翻示例
