### ISSUE TITLE
react-watermark最新版组件调用报错

### ISSUE THREAD

**Issue by xpqxpxp** [pansyjs/watermark#71]
组件内部报错
![image](https://user-images.githubusercontent.com/97508862/148907205-eadd68fd-2c75-4d74-855d-d083b9f22283.png)
![image](https://user-images.githubusercontent.com/97508862/148907228-43705eb8-529e-4a44-9702-5519cafdaae7.png)

**Comment by wangxingkang** [comment]
提供下最小复现仓库吧
