### ISSUE TITLE
react-watermark 导入组件报错

### ISSUE THREAD

**Issue by jiangkaifree** [pansyjs/watermark#78]
### 问题描述

从 `react-watermark` 中导入 `Watermark` 组件 报错。
![image](https://user-images.githubusercontent.com/50451924/154441163-64edbae6-a5a0-40f6-8c83-724d04386529.png)

### 复现步骤

1. create-react-app 创建项目
2. App.jsx  导入组件 
```js
import Login from './components/Login/Login';
import { Watermark } from '@pansy/react-watermark';

function App() {
  return (
      <main>
        <Login />
      </main>
  );
}
export default App;
```
3. 项目运行报错 错误信息  Internal server error: Failed to resolve import "@pansy/react-watermark" from "src\App.jsx". Does the file exist?

### 环境详情

- **`@pansy/watermark` version:**
- **`react` version:*17.0.2*
- **`react-dom` version:*17.0.2*
- **`typescript` version:**

**Comment by wangxingkang** [comment]
我看下

**Comment by wangxingkang** [comment]
能提供下最小复现仓库？

**Comment by jiangkaifree** [comment]
晚点




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pansyjs/watermark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月17日(星期四) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pansyjs/watermark] react-watermark 导入组件报错 (Issue #78)





 
能提供下最新复现仓库？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiangkaifree** [comment]
现在好像好了

**Comment by jiangkaifree** [comment]
可以补充一下文档

**Comment by wangxingkang** [comment]
OK

**Comment by wangxingkang** [comment]
那先关了，有问题再打开

**Comment by jiangkaifree** [comment]
能否文档的快速上手，加上一段， 不然并不知道 react vue 对应的包的名称（我有提交pr），我看了一下在常见问题在有说明，但是上手，第一时间大概率是不会去这里翻找的
