### ISSUE TITLE
@pansy/vue-watermark包没有找到

### ISSUE THREAD

**Issue by LiXunGuan** [pansyjs/watermark#86]
文档里面写着有`@pansy/vue-watermark`包但是没有找到

**Comment by wangxingkang** [comment]
目前还没写，最近有点忙，有没有兴趣提个PR

**Comment by wangxingkang** [comment]
目前只有   react 版本

**Comment by LiXunGuan** [comment]
=，=  不是很熟悉组件开发

**Comment by haiweilian** [comment]
> 目前还没写，最近有点忙，有没有兴趣提个PR

我最近用到了这个插件，用的 core 包，我这两天试试封装下 vue2/3 的。

**Comment by LiXunGuan** [comment]
我看到项目vue功能已经更新了，觉得可以补充一下文档。

**Comment by wangxingkang** [comment]
欢迎PR
