### ISSUE TITLE
bro, 直接chrome隐藏元素或者禁用js删除水印dom，是不是无解呢

### ISSUE THREAD

**Issue by wenyuanzhuo** [pansyjs/watermark#93]
### 环境详情

- **`@pansy/watermark` version:**
- **`react` version:**
- **`react-dom` version:**
- **`typescript` version:**

**Comment by wangxingkang** [comment]
禁用 js 那肯定无解

**Comment by wangxingkang** [comment]
隐藏元素 是什么场景

**Comment by wangxingkang** [comment]
暂时关闭了 有问题再重新打开
