### ISSUE TITLE
能否支持盲水印

### ISSUE THREAD

**Issue by crazyair** [pansyjs/watermark#97]

**Comment by wangxingkang** [comment]
暗水印 是啥

**Comment by crazyair** [comment]
> 暗水印 是啥

https://baijiahao.baidu.com/s?id=1725281556196224130&wfr=spider&for=pc

**Comment by crazyair** [comment]
> 

这个功能是否考虑加进来 https://www.cnblogs.com/Miracle-ZLZ/p/14137350.html

**Comment by wangxingkang** [comment]
欢迎PR

**Comment by wangxingkang** [comment]
v2.1.0
